### ISSUE TITLE
Support for placeholders, @ commands?

### ISSUE THREAD

**Issue by stefandevo** [BearToCode/carta-md#11]
Nice Job!

Would it be possible to add some kind of placeholder support?
Something like type `@` and then get a list of possible names etc to be inserted.
But then again, not able to adjust any of the name/placeholder without first removing it again (so not just adding the text)?

**Comment by BearToCode** [comment]
Hi! From what I understand you'd like a list to pop up when you type `@`, and to be able to select on the list options to generate some predefined text. That's kind of similar to what the slash/emoji plugins do, and you can create an extension that do that. 
You can look at `packages/plugin-emoji/src/lib` for a reference, there is a bit of boilerplate but you get an idea.

However I do not understand what you mean with "not being able to adjust any of the name/placeholder without first removing it again": you don't want the user to modify the created text? In this case the first thing it comes to my mind is to listen for values change and, if the change modifies one of the "placeholder" texts, just revert it back, but I'm not sure that's what you meant.

**Comment by BearToCode** [comment]
Hello again,
regarding positioning elements next to the cursor: I added a new function in the latest version which makes positioning elements next to the caret much easier. Here's an example:
```svelte
<script>
  // ...

  export let carta;

  let caretPosition;
  let elem;

  onMount(() => {
    carta.input.addEventListener('input', handleInput);
  });

  onDestroy(() => {
    carta.input.removeEventListener('input', handleInput);
  });

  function handleInput() {
  	 caretPosition = carta.input.getCursorXY();
  }

  $: {
    caretPosition, elem.clientWidth, elem.clientHeight;
    carta.input.moveElemToCaret(elem);
  }
</script>

<div bind:this={elem}>
  <!-- My stuff -->
</div>
```
To use the new `moveElemToCaret` function, you need to update to version 2.3.0.

About deleting the whole name: while the editor you mentioned is node based, Carta only uses pure text. For this reason, you need to manually check for changes/override the default functionality, but you can definetely do that. For example:
- Listen for inputs and check for invalid tags, remove them if any is found,
- Listen for caret(cursor) movement(using keyboards keys and clicks) and if it is over a tag, move the caret away.

I also suggest you add a custom hightlight rule to make tags prettier, you can look at `plugin-math` for an example but basically you need to add this prop to the extension:
```ts
shjRef: (shj) => {
	import('./lang.js')
		.then((module) => shj.loadCustomLanguage('langName', module))
		.then(() => carta.input?.update());
}
```
Where `lang.js` is just a file containing highlight rules, for example in your case
```ts
export default [
	{
		match: /\B@\w+/g,
		type: 'str'
	},
]
```

Let me know if you have any issue
