### ISSUE TITLE
FYI http://beartocode.me not working (anymore)

### ISSUE THREAD

**Issue by stefandevo** [BearToCode/carta-md#12]
The referenced domain is not working currently.

**Comment by BearToCode** [comment]
Thanks for the info. The domain expired but I have already updated the links in the repo and in the latest README on npm.

**Comment by stefandevo** [comment]
<img width="555" alt="CleanShot 2023-09-04 at 13 26 29@2x" src="https://github.com/BearToCode/carta-md/assets/1656051/6214061a-dc73-4f25-addd-3a1cbce8c8d3">

is also in the "About" section FYI

**Comment by BearToCode** [comment]
Missed that! Thanks!
