### ISSUE TITLE
Inconsistent Marked Version?

### ISSUE THREAD

**Issue by ysk3a** [BearToCode/carta-md#17]
Hello,
Awesome library.
I was playing around with this library and see how it would look for an app I am making. I'm also using Markedjs (version 9.1.5) library itself in a different part of my app. 
but I noticed that markedjs version is different in cartamd.
After doing a brief search in this repository, I'm seeing 4.3.0 or 6.0.0. 
I've also gotten a warning in the terminal:
```
 WARN  Issues with peer dependencies found
.
└─┬ @cartamd/plugin-emoji 2.7.2
  └── ✕ unmet peer marked@^4.3.0: found 9.1.5
```

**Comment by BearToCode** [comment]
Hi, thanks for pointing that out.
I've now made sure all packages reference the same version, and I've also took the opportunity to update to the latest version (`9.1.5`).

**Comment by BearToCode** [comment]
Hello again,
you are right! This is just me forgetting to rename them after lazily copy pasting the readmes. I'll fix them soon. 
Thanks
