### ISSUE TITLE
Some CSS styles break the editor

### ISSUE THREAD

**Issue by styxpilled** [BearToCode/carta-md#2]
I had it working great in a tiny side project, so I decided to bring it into my main work project. Everything seemed fine, but when playing around something seemed off. The caret didn't match up with what I was selecting, and text would appear in totally unexpected places.
Turns out my root styles (CSS Remedy that I stole from Tailwind and my general root styles) were overriding the `<textarea />` that Carta uses for input (really cool btw, hadn't thought of that).

So if anyone in the future is struggling, check what styles apply to the `#md textarea`, especially width, height and line-height.

Sidenote, maybe we could increase the [selector specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) for some of the internal elements like textarea? I think the styles that were causing trouble for me were just
```css
textarea {
   /* Whatever the hell it was */
}
```
having a specificity of (0, 0, 1). I think maybe changing the `textarea` selector in `MarkdownInput.svelte` to `.carta-input > textarea` would help?

**Comment by BearToCode** [comment]
Hi again @styxpilled!
Regarding selector specificity, despite vscode showing a (0,0,1) on hover, when Svelte compiles the components it adds a unique class to that element, (for example `textarea` becomes `textarea.s-XUCSmWdeYaCN`), so it will override global `textarea` selectors. I don't think it is a good idea to go beyond class level selectors.

Anyway, I'm also using using carta Carta in a TailwindCSS project, and I did not experience that issue, as global stylesheets usually do not use ids. There was a bug that caused misalignment when switching tabs after not typing anything(not styles related), but it should be fixed in v1.1.10. Let me know if you experience it again.

**Comment by styxpilled** [comment]
So I looked into this again. I had three issues:

#### 1. Textarea width gets overridden if you have a global `textarea` selector with at least two `:not` pseudo-classes
This snippet:
```css
textarea:not(.fit, .auto) {
  width: 3rem;
}
```
Had a higher specificity than the MarkdownInput.svelte styles:
![image](https://github.com/BearToCode/carta-md/assets/95433744/24ef870b-fae6-4b0f-974b-c5f903e28f20)

Which is a fun lesson about the :not pseudo-class, I suppose. The Carta styles gets overridden if you have 2 or more :not() pseudo-classes (which I can see happening). Which is why relying on svelte hashing isn't always enough, and you need to look at selector specificity, especially in components. Style hashing is mostly to keep the styles from leaking.

#### 2. Carta doesn't set `max-width` on the textarea
This snippet:
```css
textarea {
  max-width: 20rem;
}
```
will just override Carta. I'll submit a PR to add `max-width: 100%` later.


#### 3. Setting `font-family` to inherit with a textarea selector fucks up the whole thing.
This snippet:
```css
textarea {
  font-family: inherit;
}
```
Will mess up the entire editor.

![image](https://github.com/BearToCode/carta-md/assets/95433744/5c623918-f3cf-4448-954e-7a4c42c8c6e8)
I think this is because `pre` tags use `monospace` from the user agent. Giving a textarea `font-family: inherit` will make them use different fonts and not line up. Although I'm not sure where the textarea is getting monospace in the first place...

A bit of a mess but since my original issue was about these things (I just commented out the styles instead of diving into what's really going on) I thought that I'll just continue it here

**Comment by BearToCode** [comment]
I guess points 2 & 3 can be easily fixed. I'll look into them tomorrow
